export const UPDATE_TEMPERATURE = "UPDATE_TEMPERATURE";
export const UPDATE_HUMIDITY = "UPDATE_HUMIDITY";
export const UPDATE_WIND_STRENGTH = "UPDATE_WIND_STRENGTH";
export const UPDATE_GUST_STRENGTH = "UPDATE_GUST_STRENGTH";
export const UPDATE_RAIN_24H = "UPDATE_RAIN_24H";
export const UPDATE_RAIN_60MIN = "UPDATE_RAIN_60MIN";
export const UPDATE_RAIN_LIVE = "UPDATE_RAIN_LIVE";
